# Generated by Django 5.2 on 2025-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10)),
                ('is_sold', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
